### ISSUE TITLE
Published pngencoder-0.12.0.pom contains <name>${project.groupId}:${project.artifactId}</name>

### ISSUE THREAD

**Issue by simon04** [pngencoder/pngencoder#21]
https://repo1.maven.org/maven2/com/pngencoder/pngencoder/0.12.0/pngencoder-0.12.0.pom contains

> <name>${project.groupId}:${project.artifactId}</name>

… causing an awkward display in IntelliJ's dependencies view:

![image](https://user-images.githubusercontent.com/782446/164165553-f78ed024-22a8-4206-9302-cf3e59e07dc4.png)

**Comment by johantiden** [comment]
:scream:

**Comment by johantiden** [comment]
I'll just hardcode it to `com.pngencoder:pngencoder`

**Comment by johantiden** [comment]
Will be fixed with next release to `maven.org`
