### ISSUE TITLE
Improve README with example usages of withPredictorEncoding

### ISSUE THREAD

**Issue by johantiden** [pngencoder/pngencoder#26]

**Comment by rototor** [comment]
You should also mention that now 16-Bit images, grayscale images and color profiles are supported now. 

Only very "strange" image formats like BufferedImage.TYPE_USHORT_565_RGB are not supported and fallback to sRGB encoding.

**Comment by johantiden** [comment]
I think the examples do well to show the predictor. I don't know why we didn't close this before. Closing it now.
