### ISSUE TITLE
Indexed images encode incorrectly

### ISSUE THREAD

**Issue by jackrusher** [pngencoder/pngencoder#34]
We're seeing a bug where converting a low-color image that arrived as a GIF fails with what look like stride problems using version `0.13.0` on JDK 11/17 on Linux and Mac.

Using `ImageIO` to read the image at https://etc.usf.edu/clipart/36600/36667/thermos_36667_sm.gif and then encoding it with PNGEncoder, results in:

![example](https://user-images.githubusercontent.com/220188/174032264-e18dfd6d-e3fe-44ec-980b-7eba3b2dd809.png)

For a second example, https://nextjournal.com/data/QmUyFWw9L8nZ6wvFTfJvtyqxtDyJiAr7EDZQxLVn64HASX?filename=Requiem-Ornaments-Byline.png&content-type=image/png renders as:

![example-2](https://user-images.githubusercontent.com/220188/174032601-9ac46194-dd20-4509-b55b-e66855e18054.png)

**Comment by johantiden** [comment]
Thanks for reporting! Can the same problem be seen in `0.12.0`? Special grayscale handling was implemented in `0.13.0`, we'd need to check if this is a regression there.

**Comment by johantiden** [comment]
I can reproduce corrupted pngs using the code below:
`ImageIO` reads the gif as `TYPE_BYTE_INDEXED`, which seems to cause the issue, even if I create a new `TYPE_BYTE_INDEXED` image from scratch.
 
```
public class GrayscaleTest {
    @Test
    void testGrayscaleGifShouldBeSavedProperly() throws IOException {

        final BufferedImage bufferedImage = PngEncoderTestUtil.readTestImageResource("thermos_36667_sm.gif");

        byte[] png = new PngEncoder().withBufferedImage(bufferedImage)
                .toBytes();

        new PngEncoder().withBufferedImage(bufferedImage)
                .toFile("out.png");

        BufferedImage unpacked = ImageIO.read(new ByteArrayInputStream(png));

//        PngEncoderTestUtil.encodeWithImageIO(bufferedImage);

        assertEquals(bufferedImage, unpacked);
    }

    @Test
    void testGrayscaleSynthetic() throws IOException {
        BufferedImage bufferedImage = new BufferedImage(1, 2, 13);
        Graphics g = bufferedImage.getGraphics();

        g.setColor(new Color(4, 4, 4));
        g.drawRect(0, 0, 1, 1);

        g.setColor(new Color(255, 255, 255));
        g.drawRect(0, 0, 1, 1);


        byte[] png = new PngEncoder().withBufferedImage(bufferedImage)
                .toBytes();

        new PngEncoder().withBufferedImage(bufferedImage)
                .toFile("out.png");

        BufferedImage unpacked = ImageIO.read(new ByteArrayInputStream(png));

        //        PngEncoderTestUtil.encodeWithImageIO(bufferedImage);

        assertEquals(bufferedImage, unpacked);

    }
}
```

**Comment by johantiden** [comment]
Using the above tests, I can bisect (good) from `0.12.0` and end up with this:
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
211e15651c038d450424cb0aa3b89c54af7139a3
6f746d61797047e9a77f6dc58a884c5f295f19a5
fde79e6001c4edb26134c95fc99c24c976a48681
1377b0a520c681d1e5d28792ad7a7c1128dadde3
20e2a308e256ed1a6e7b7fc3a90294c081a35863
49d4561db23370b1c63d976e618905b4284b0fe8
We cannot bisect more!
```

**Comment by johantiden** [comment]
@jackrusher What is the license on those images? Can we use them regression testing? I've added this branch for now: bugfix/34-grayscale

**Comment by johantiden** [comment]
> Can the same problem be seen in `0.12.0`? Special grayscale handling was implemented in `0.13.0`, we'd need to check if this is a regression there.

`0.12.0` works fine. It encodes the image with the wrong format (`TYPE_3BYTE_BGR`) - wasting space - but it should at least work as expected.

**Comment by jackrusher** [comment]
@johantiden Thanks for looking into this! The first image is under a [friendly license](https://etc.usf.edu/clipart/info/license) from a University, the second is public domain from Wikipedia, so I think they're both fine for a regression test :)

**Comment by johantiden** [comment]
```
    @Test
    void showcaseMismatchInNumberOfChannels() {
        final BufferedImage image = getRealGifImage();

        WritableRaster imageRaster = image.getRaster();
        final int channels = imageRaster.getSampleModel().getNumBands();

        PngEncoderScanlineUtil.EncodingMetaInfo metaInfo = PngEncoderScanlineUtil.getEncodingMetaInfo(image);

        assertEquals(channels, 1);
        assertEquals(metaInfo.channels, 1); // actual is 3
    }
```
The `IHDR` gets `IHDR_COLOR_TYPE_RGB` (=2) but we only write one channel in the actual data, causing the corruption when reading.

**Comment by johantiden** [comment]
You could use this workaround for now if you want. Re-draw any image that has type `BufferedImage.TYPE_BYTE_INDEXED` into another type (e.g. `BufferedImage.TYPE_3BYTE_BGR`) before encoding it.
```
    @Test
    void testWorkaround() throws IOException {
        BufferedImage bufferedImage = PngEncoderTestUtil.readTestImageResource("thermos_36667_sm.gif");

        if (bufferedImage.getType() == BufferedImage.TYPE_BYTE_INDEXED) {
            final BufferedImage bgr = new BufferedImage(bufferedImage.getWidth(), bufferedImage.getHeight(), BufferedImage.TYPE_3BYTE_BGR);
            bgr.getGraphics().drawImage(bufferedImage, 0, 0, null);
            bufferedImage = bgr;
        }

        byte[] png = new PngEncoder().withBufferedImage(bufferedImage)
                .toBytes();

        BufferedImage unpacked = ImageIO.read(new ByteArrayInputStream(png));

        PngEncoderTestUtil.assertThatImageIsEqual(unpacked, bufferedImage);
    }
```

**Comment by johantiden** [comment]
[ca1973c](https://github.com/pngencoder/pngencoder/commit/ca1973ce36ef23f89f90ae026b2e60c8fd02c095)
Skip arraycopy for indexed images.

The "thermos" image ends up like this:
![out](https://user-images.githubusercontent.com/22770524/183855904-4274074b-4c13-4da5-8c42-54d50a953330.png)

**Comment by johantiden** [comment]
Also adding [37](https://github.com/pngencoder/pngencoder/issues/37)

**Comment by johantiden** [comment]
Fixed in https://github.com/pngencoder/pngencoder/tree/0.13.1

**Comment by johantiden** [comment]
It will take a while to show up in maven central. I don't have the keys anymore :(
Ping @jkaving

**Comment by johantiden** [comment]
It should now be available in maven central!
```
<dependency>
  <groupId>com.pngencoder</groupId>
  <artifactId>pngencoder</artifactId>
  <version>0.13.1</version>
</dependency>
```

**Comment by mk** [comment]
@johantiden awesome, thank you!
