### ISSUE TITLE
Call the newly created Deflater's end() in non multithread compression

### ISSUE THREAD

**Issue by rsoti** [pngencoder/pngencoder#70]
First of all let me say your mutlithread compression's speed is amazingin.
In my I use case I need to use the single thread compression: withMultiThreadedCompressionEnabled(false). I noticed that in this mode a new Deflater is created for the compression and after the compression this Deflater's end() method is not called. The explicit end() call releases native memory immediately. Without that the "end" is invoked by the "finalizer" when the objects go through GC. In this case our system went into what seems like native memory leak.
I propose to call end() at the end of single thread compression.

**Comment by johantiden** [comment]
I just released 0.15.0 to sonatype. It will be published shortly!
